### ISSUE TITLE
Improve Travis CI clang installation

### ISSUE THREAD

**Issue by lulivi** [rticommunity/rticonnextdds-examples#259]
Use [Travis CI apt addon](https://docs.travis-ci.com/user/installing-dependencies/) to install clang sources.

Example:

```yml
addons:
  apt:
    sources:
    - deadsnakes
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'deb https://packagecloud.io/chef/stable/ubuntu/precise main'
    - key_url: 'https://packagecloud.io/gpg.key'
```
